<?php

/**
 * Keyword deteksi transaksi (fast path ProcessIncomingMessage).
 *
 * - transaction_keywords: daftar utama (deduplicated).
 * - extra_transaction_keywords: tambahan tanpa overlap dengan daftar utama.
 * - short_ambiguous_transaction_keywords: pakai word boundary, bukan str_contains.
 */
return [

    'transaction_keywords' => [
        'makan', 'makan pagi', 'makan siang', 'makan malam', 'sarapan', 'breakfast', 'lunch', 'dinner',
        'mkn', 'maem', 'mamam', 'nyemil', 'ngemil', 'cemilan', 'snack', 'warteg',
        'warung', 'resto', 'restoran', 'cafe', 'kafe', 'kantin', 'foodcourt', 'geprek',
        'gorengan', 'bakwan', 'siomay', 'batagor', 'pempek', 'empek', 'cilok', 'cireng',
        'soto', 'rawon', 'rendang', 'gudeg', 'pecel', 'gado', 'ketoprak', 'bubur',
        'lontong', 'sate', 'bakso', 'nasgor', 'nasi uduk', 'nasi campur', 'ayam geprek', 'ayam goreng',
        'martabak', 'terang bulan', 'roti', 'donat', 'kue', 'roti bakar', 'indomie', 'mie ayam',
        'mie goreng', 'nasi goreng', 'nasgep', 'mie instant', 'kwetiau', 'bakmi', 'capcay', 'gado-gado',
        'rujak', 'kolak', 'es buah', 'es cendol', 'es campur', 'es dawet', 'tahu', 'tempe',
        'telur', 'ikan', 'sayur', 'daging', 'udang', 'cumi', 'seafood', 'nasi liwet',
        'nasi kuning', 'nasi putih', 'nasi goreng seafood', 'nasi bakar', 'shawarma', 'kebab', 'burger', 'hotdog',
        'pizza', 'pasta', 'sushi', 'ramen', 'dimsum', 'sop', 'soto ayam', 'soto sapi',
        'soto babat', 'soto betawi', 'soto lamongan', 'bakso urat', 'bakso mercon', 'bakso bakar', 'mie bakso', 'cimol',
        'seblak', 'basreng', 'baso aci', 'es krim', 'ice cream', 'gelato', 'sundae', 'milkshake',
        'smoothie', 'lumpia', 'risoles', 'pastel', 'pisang goreng', 'pisgor', 'tahu isi', 'tempe mendoan',
        'opor', 'opor ayam', 'opor telur', 'sambal', 'lalapan', 'nasi tim', 'nasi kucing', 'tahu gejrot',
        'tahu sumedang', 'ayam crispy', 'ayam krispi', 'bakwan malang', 'lontong balap', 'rujak cingur', 'lontong sayur', 'coto',
        'coto makassar', 'konro', 'pallubasa', 'nasu liku', 'kapurung', 'pempek lenjer', 'pempek kapal selam', 'model',
        'tekwan', 'mie celor', 'mie rebus', 'mie kuah', 'kwetiau goreng', 'kwetiau kuah', 'nasi timbel', 'nasi tutug',
        'nasi tumpeng', 'nasi box', 'nasi kotak', 'tumpeng', 'lontong dekem', 'ketupat', 'sate madura', 'sate padang',
        'sate kambing', 'sate ayam', 'sate sapi', 'lotek', 'karedok', 'urap', 'tumis', 'oseng',
        'tahu campur', 'rawon setan', 'soto ceker', 'soto daging', 'es doger', 'es teler', 'es kelapa', 'es kelapa muda',
        'kelapa muda', 'es degan', 'es alpukat', 'mcd', 'mcdonalds', 'kfc', 'aw', 'hokben',
        'yoshinoya', 'solaria', 'warunk upnormal', 'starbucks', 'sbux', 'sbx', 'janji jiwa', 'kopi kenangan',
        'fore', 'tomoro', 'mixue', 'chatime', 'gulu gulu', 'xiboba', 'boba', 'pizza hut',
        'phd', 'dominos', 'burger king', 'wendys', 'jco', 'dunkin', 'krispy kreme', 'kopi kapal api',
        'kopi abc', 'teh botol', 'teh pucuk', 'teh gelas', 'aqua', 'lemineral', 'sukabumi', 'sederhana',
        'padang', 'sari buana', 'bebek', 'bebek goreng', 'bebek bakar', 'rumah makan', 'rm', 'depot',
        'warung makan', 'warkop', 'warung kopi', 'gacoan', 'mie gacoan', 'marugame', 'marugame udon', 'ippudo',
        'sederhana bintaro', 'bakmi gm', 'bakmi ae', 'bakso boedjangan', 'es teller', 'abc', 'indomilk', 'ultra',
        'dancow', 'good day', 'torabika', 'nescafe', 'max tea', 'teh kotak', 'ngopi', 'kopi',
        'coffee', 'teh', 'es teh', 'esteh', 'es jeruk', 'jus', 'juice', 'susu',
        'minum', 'cappuccino', 'latte', 'americano', 'espresso', 'matcha', 'coklat', 'chocolate',
        'es kopi', 'kopi susu', 'kopi tubruk', 'kopi sachet', 'es coklat', 'teh tarik', 'teh manis', 'teh hangat',
        'teh dingin', 'jus alpukat', 'jus jeruk', 'jus mangga', 'jus jambu', 'jus melon', 'soda', 'soft drink',
        'coca cola', 'coca-cola', 'pepsi', 'fanta', 'sprite', 'minuman', 'ngeteh', 'beli',
        'bayar', 'belanja', 'jajan', 'borong', 'checkout', 'order', 'pesen', 'pesan',
        'shopee', 'tokped', 'tokopedia', 'lazada', 'bukalapak', 'blibli', 'olshop', 'online shop',
        'alfamart', 'indomaret', 'alfamidi', 'superindo', 'hypermart', 'carrefour', 'giant', 'lotte',
        'sembako', 'minyak', 'beras', 'gula', 'sayur mayur', 'bumbu', 'bahan masak', 'bahan dapur',
        'pasar', 'pasar tradisional', 'pasar modern', 'minimarket', 'supermarket', 'toko', 'toko kelontong', 'toko online',
        'marketplace', 'flash sale', 'diskon', 'promo', 'voucher', 'cashback', 'elevenia', 'jd id',
        'jd.id', 'zalora', 'sociolla', 'buku', 'alat tulis', 'perlengkapan', 'kebutuhan rumah', 'kebutuhan sehari-hari',
        'pakaian', 'baju', 'celana', 'sepatu', 'tas', 'aksesoris', 'elektronik', 'gadget',
        'hp', 'handphone', 'laptop', 'charger', 'earphone', 'bensin', 'pertamax', 'pertalite',
        'solar', 'isi bensin', 'ngisi bensin', 'parkir', 'transport', 'transportasi', 'ongkos', 'ongkir',
        'kirim', 'pengiriman', 'grab', 'gojek', 'ojol', 'ojek', 'ojek online', 'maxim',
        'indriver', 'taxi', 'taksi', 'bluebird', 'angkot', 'busway', 'transjakarta', 'mrt',
        'lrt', 'krl', 'kereta', 'toll', 'tol', 'etoll', 'e-toll', 'tiket',
        'pesawat', 'bus', 'travel', 'naik', 'naik ojek', 'naik grab', 'naik gojek', 'naik taxi',
        'perjalanan', 'pergi', 'pulang', 'damri', 'travel bandung', 'travel jogja', 'kereta api', 'kai',
        'garuda', 'lion air', 'batik air', 'citilink', 'tiket kereta', 'tiket pesawat', 'tiket bus', 'tiket travel',
        'spbu', 'pom bensin', 'isitron', 'shell', 'total', 'pertamina', 'go ride', 'go car',
        'grab bike', 'grab car', 'grab express', 'listrik', 'pln', 'air', 'pdam', 'internet',
        'wifi', 'indihome', 'biznet', 'firstmedia', 'pulsa', 'kuota', 'paket data', 'top up',
        'topup', 'isi pulsa', 'isi kuota', 'bpjs', 'asuransi', 'pajak', 'pbb', 'stnk',
        'sim', 'tagihan', 'bayar listrik', 'bayar air', 'bayar internet', 'bayar pulsa', 'token listrik', 'token pln',
        'bayar bpjs', 'premi asuransi', 'telkom', 'telkomsel', 'indosat', 'xl', 'axis', 'three',
        'smartfren', 'by.u', 'kartu perdana', 'paket internet', 'paket nelpon', 'cicilan motor', 'cicilan mobil', 'angsuran rumah',
        'kpr', 'nonton', 'bioskop', 'cinema', 'xxi', 'cgv', 'cinepolis', 'netflix',
        'spotify', 'youtube', 'disney', 'vidio', 'viu', 'wetv', 'iqiyi', 'game',
        'steam', 'playstation', 'ps', 'xbox', 'mobile legend', 'ml', 'ff', 'pubg',
        'valorant', 'konser', 'tiket konser', 'tiket musik', 'event', 'tiket event', 'futsal', 'badminton',
        'gym', 'fitness', 'yoga', 'renang', 'olahraga', 'tiket film', 'tiket bioskop', 'premiere',
        'imax', '4dx', 'dota', 'dota 2', 'lol', 'league of legends', 'genshin', 'honkai',
        'free fire', 'mobile legends', 'csgo', 'cs2', 'tiket wisata', 'tiket masuk', 'taman bermain', 'dunia fantasi',
        'dufan', 'ancol', 'taman safari', 'waterboom', 'dunia laut', 'karaoke', 'karaoke box', 'main game',
        'warnet', 'rental ps', 'gpt', 'chatgpt', 'openai', 'gemini', 'claude', 'api',
        'copilot', 'cursor', 'canva', 'figma', 'adobe', 'premium', 'prem', 'langganan',
        'subscription', 'subs', 'apk', 'app', 'aplikasi', 'software', 'license', 'lisensi',
        'cloud', 'hosting', 'domain', 'server', 'vps', 'microsoft', 'office 365', 'google one',
        'dropbox', 'icloud', 'notion', 'slack', 'zoom', 'teams', 'discord nitro', 'apple music',
        'deezer', 'tidal', 'apple tv', 'hbo', 'prime video', 'gaji', 'bonus', 'terima',
        'transfer', 'tf', 'trf', 'terima duit', 'dapat duit', 'dapet duit', 'honor', 'upah',
        'THR', 'komisi', 'fee', 'bayaran', 'penghasilan', 'income', 'uang masuk', 'duit masuk',
        'masuk', 'penjualan', 'omset', 'jual', 'dapat', 'dapet', 'diterima', 'dibayar',
        'lunas', 'invoice dibayar', 'invoice lunas', 'pembayaran diterima', 'fee project', 'honorarium', 'tunjangan', 'uang lembur',
        'dividen', 'bunga deposito', 'bunga tabungan', 'laku', 'laris', 'order masuk', 'orderan', 'dp masuk',
        'down payment', 'piutang lunas', 'piutang masuk', 'tagihan dibayar', 'closing', 'deal', 'cash masuk', 'tunai masuk',
        'hasil jualan', 'untung', 'profit', 'cuan', 'pembayaran customer', 'bayar customer', 'pelanggan bayar', 'modal',
        'kulakan', 'stok', 'stock', 'restock', 'restok', 'bahan baku', 'bahan', 'supplier',
        'vendor', 'distributor', 'grosir', 'agen', 'packaging', 'packing', 'kemasan', 'kardus',
        'plastik packing', 'ongkir kirim', 'kirim barang', 'ekspedisi', 'jne', 'jnt', 'sicepat', 'anteraja',
        'operasional', 'biaya operasional', 'sewa toko', 'sewa gudang', 'sewa ruko', 'gaji pegawai', 'upah pegawai', 'bayar karyawan',
        'tiktok shop', 'shopee pay', 'cod', 'dropship', 'reseller', 'biaya produksi', 'biaya bahan', 'biaya kirim',
        'biaya packing', 'sewa', 'kos', 'kost', 'kontrakan', 'kontrak', 'ngontrak', 'cicilan',
        'kredit', 'angsuran', 'sewa rumah', 'sewa kamar', 'sewa kantor', 'sewa kios', 'dp rumah', 'uang muka',
        'booking fee', 'biaya notaris', 'listrik kos', 'air kos', 'biaya kos', 'bayar kos', 'ngasih', 'kasih',
        'kirimin', 'kirim ke', 'transfer ke', 'buat', 'untuk', 'ortu', 'orang tua', 'sedekah',
        'infaq', 'infak', 'zakat', 'sumbangan', 'donasi', 'amal', 'uang jajan', 'uang saku',
        'uang bulanan', 'kirim uang', 'kirim duit', 'traktir', 'mentraktir', 'treat', 'ng traktir', 'traktiran',
        'hadiah', 'kado', 'oleh-oleh', 'oleh oleh', 'obat', 'apotek', 'dokter', 'rumah sakit',
        'rs', 'puskesmas', 'klinik', 'lab', 'cek darah', 'salon', 'barbershop', 'potong rambut',
        'cukur', 'facial', 'spa', 'pijat', 'massage', 'skincare', 'makeup', 'kosmetik',
        'parfum', 'vaksin', 'checkup', 'medical', 'konsultasi dokter', 'berobat', 'optik', 'kacamata',
        'lensa', 'lensa kontak', 'cek mata', 'gigi', 'dokter gigi', 'cabut gigi', 'behel', 'scaling',
        'fisioterapi', 'rehabilitasi', 'terapi', 'obat-obatan', 'vitamin', 'suplemen', 'herbal', 'jamu',
        'spp', 'uang sekolah', 'uang kuliah', 'atk', 'kursus', 'les', 'bimbel', 'biaya sekolah',
        'mengaji', 'ngaji', 'sekolah mengaji', 'tpa', 'tpq',
        'biaya kuliah', 'registrasi', 'daftar ulang', 'uang pangkal', 'uang gedung', 'biaya praktikum', 'biaya lab', 'buku pelajaran',
        'seragam', 'alat praktek', 'ujian', 'try out', 'kursus bahasa', 'kursus programming', 'kursus desain', 'laundry',
        'cuci', 'cuci baju', 'cuci mobil', 'jasa cuci', 'jahit', 'perbaikan baju', 'bengkel', 'servis',
        'perbaikan', 'spare part', 'cuci motor', 'salon mobil', 'detailing', 'pole wax', 'service ac', 'isi freon',
        'perbaikan ac', 'bongkar pasang ac', 'tukang', 'tukang ledeng', 'tukang listrik', 'tukang cat', 'tukang kayu', 'pindah rumah',
        'jasa pindahan', 'rental truk', 'sewa mobil', 'makanan kucing', 'makanan anjing', 'pet food', 'vet', 'dokter hewan',
        'grooming', 'grooming kucing', 'grooming anjing', 'vaksin hewan', 'kandang', 'pasir kucing', 'perlengkapan hewan', 'hobi',
        'alat hobi', 'bahan craft', 'kain', 'benang', 'jarum', 'cat', 'kuas', 'kanvas',
        'alat lukis', 'fotografi', 'kamera', 'alat musik', 'gitar', 'drum', 'keyboard', 'kursus musik',
        'saham', 'reksadana', 'deposito', 'tabungan', 'investasi', 'bibit', 'bareksa', 'ajaib',
        'stockbit', 'emiten', 'beli saham', 'jual saham', 'capital gain', 'popok', 'susu formula', 'mpasi',
        'baju bayi', 'perlengkapan bayi', 'mainan anak', 'buku anak', 'les anak', 'ekstrakurikuler', 'undangan', 'catering',
        'dekorasi', 'fotografer', 'videografer', 'gedung', 'sewa gedung', 'mc', 'entertainment', 'dangdut',
        'souvenir', 'hampers', 'bunga', 'kado pernikahan', 'zakat fitrah', 'zakat mal', 'zakat penghasilan', 'qurban',
        'sedekah jariah', 'wakaf', 'infak masjid', 'kotak amal', 'abis', 'habis', 'keluar', 'kluar',
        'spending', 'spent', 'uang', 'duit', 'ngeluarin', 'keluarin', 'abis buat', 'habis buat',
        'keluar buat', 'tadi', 'barusan', 'kemarin', 'kmrn', 'semalem', 'biaya', 'pembelian',
        'pembayaran', 'makanan', 'shopping', 'check out', 'abisin', 'abisin duit', 'keluar duit', 'keluar uang',
        'buang', 'buang duit', 'buang uang', 'hambur', 'hamburin', 'trakhir', 'beliin', 'beliin buat',
        'beli buat', 'beliin ke', 'bayarin', 'bayarin buat', 'bayar buat', 'transferan', 'kasih ke', 'pengen',
        'pengen beli', 'pengen makan', 'mau beli', 'mau makan', 'baru beli', 'baru makan', 'baru bayar', 'baru keluar',
        'tadi beli', 'tadi makan', 'tadi bayar', 'kemarin beli', 'habis beli', 'habis makan', 'abis beli', 'abis makan',
        'rp', 'rupiah', 'rb', 'ribu', 'k', 'jt', 'juta', 'm',
        'seratus', 'dua ratus', 'lima ratus', 'seribu', 'dua ribu', 'lima ribu', 'sepuluh ribu', 'dua puluh ribu',
        'lima puluh ribu', 'seratus ribu', 'dua ratus ribu', 'lima ratus ribu', 'satu juta', 'dua juta', 'lima juta', 'sepuluh juta',
        'ngopi pagi', 'ngopi sore', 'jemput', 'antar', 'antar jemput', 'antar anak', 'jemput anak', 'bayar utang',
        'bayar hutang', 'terima piutang', 'bayar piutang', 'bayar cicilan', 'bayar angsuran', 'lunas cicilan', 'jasa', 'jasa kirim',
        'kurir', 'ninja', 'pickup', 'delivery', 'ongkos kirim', 'service', 'maintenance', 'perawatan',
        'ganti oli', 'ganti ban', 'service motor', 'service mobil', 'perbaikan hp', 'perbaikan laptop', 'ganti layar', 'ganti baterai',
        'bihun', 'bihun goreng', 'tahu goreng', 'tempe goreng', 'telur dadar', 'telur ceplok', 'ayam bakar', 'ikan bakar',
        'ikan goreng', 'tumis sayur', 'sayur bening', 'sayur asam', 'kopi hitam', 'kopi manis', 'nasi', 'lauk',
        'lauk pauk', 'gas', 'gas lpg', 'gas elpiji', 'tabung gas', 'tv kabel', 'kabel tv', 'first media',
        'streaming', 'kartu kredit', 'bayar kartu kredit', 'cicilan kartu kredit', 'alat kantor', 'kertas', 'tinta', 'toner',
        'printer', 'amplop', 'map', 'stempel', 'alat tulis kantor', 'fotokopi', 'print', 'print dokumen',
        'jilid', 'tanaman', 'pot', 'pupuk', 'pestisida', 'bibit tanaman', 'taman', 'landscape',
        'tukang taman', 'sepatu lari', 'kaos olahraga', 'celana training', 'treadmill', 'dumbell', 'matras yoga', 'alat fitness',
        'langganan gym', 'membership gym', 'personal trainer', 'hotel', 'penginapan', 'villa', 'resort', 'tiket wahana',
        'wisata', 'liburan', 'rental motor', 'rental mobil', 'sewa motor', 'premi', 'asuransi jiwa', 'asuransi kesehatan',
        'asuransi mobil', 'asuransi motor', 'asuransi rumah', 'administrasi bank', 'biaya transfer', 'biaya admin', 'smartphone', 'tablet',
        'powerbank', 'kabel data', 'headphone', 'speaker', 'webcam', 'mouse', 'monitor', 'ssd',
        'hardisk', 'furniture', 'meja', 'kursi', 'lemari', 'kasur', 'spring bed', 'sofa',
        'rak', 'lampu', 'dekorasi rumah',
    ],

    'extra_transaction_keywords' => [
        'cilor', 'cuanki', 'cilung', 'telor gulung', 'pentol', 'pentol cilok', 'tahu bulat', 'tahu bulat crispy',
        'dimsum frozen', 'dimsum ayam', 'dimsum udang', 'dimsum halal', 'dimsum kukus', 'martabak mini', 'martabak telor', 'martabak manis',
        'terang bulan mini', 'roti sobek', 'roti canai', 'roti maryam', 'roti cane', 'roti john', 'nasi padang', 'nasi padang bungkus',
        'nasi padang porsi', 'nasi kuning box', 'nasi box acara', 'nasi tumpeng mini', 'ayam penyet', 'ayam penyet sambel', 'ayam serundeng', 'ayam lalapan',
        'ikan bakar padang', 'ikan goreng tepung', 'ikan asin', 'sop buntut', 'sop kaki', 'sop iga', 'rawon daging', 'rawon ceker',
        'ketoprak jakarta', 'gado gado betawi', 'pecel lele', 'lele goreng', 'pecel ayam', 'bebek hitam', 'bebek goreng h slamet', 'wedang ronde',
        'bandrek', 'bajigur', 'cin cau', 'cincau', 'cendol durian', 'kopi item', 'kopi tarik', 'kopi susu gula aren',
        'brown sugar', 'gula aren', 'gula semut', 'krimer', 'susu oat', 'bubble tea', 'boba drink', 'cheese tea',
        'fruit tea', 'air mineral', 'air galon', 'isi ulang galon', 'gas 3 kg', 'gas melon', 'warmindo', 'depot es',
        'kedai kopi', 'coffee shop', 'indomaret point', 'alfamart klaster', 'transmart', 'pizza hut delivery', 'dominos pizza', 'sushi tei',
        'sushi hiro', 'sushi master', 'hanamasa', 'shabu hachi', 'all you can eat', 'ayce', 'buffet', 'prasmanan',
        'shopee food', 'gofood', 'grabfood', 'grab mart', 'tokopedia cod', 'lazada flash', 'live shopping', 'live tiktok',
        'checkout shopee', 'keranjang shopee', 'wishlist', 'pre order', 'po barang', 'open po', 'close po', 'slot terbatas',
        'cod area', 'kirim hari ini', 'same day', 'instant delivery', 'minimarket terdekat', 'indogrosir', 'lotus', 'in drive',
        'maxim food', 'ojek pangkalan', 'ojek halang', 'angkot jurusan', 'metromini', 'kopaja', 'travel door to door', 'travel antar kota',
        'charter mobil', 'rental harian', 'sewa harian', 'lepas kunci', 'parkir mall', 'parkir basement', 'parkir bulanan', 'kartu parkir',
        'e toll', 'mandiri e toll', 'brizzi', 'flazz', 'tapcash', 'emoney', 'isi saldo e toll', 'top up flazz',
        'isi flazz', 'token listrik pln', 'beli token', 'listrik token', 'bayar wifi', 'bayar indihome', 'bayar firstmedia', 'bayar mnc play',
        'netflix premium', 'spotify premium', 'youtube premium', 'wetv vip', 'disney plus', 'hbo go', 'prime amazon', 'vidio platinum',
        'google play', 'app store', 'play store', 'in app purchase', 'pulsa data', 'paket sms', 'roaming', 'omzet harian',
        'closing harian', 'closing kasir', 'kas kecil', 'kas besar', 'modal dagang', 'beli stok', 'stock opname', 'opname',
        'nota manual', 'nota digital', 'invoice proforma', 'dp proyek', 'termin pembayaran', 'bayar termin', 'sisa termin', 'fee jasa',
        'jasa desain', 'jasa foto', 'jasa video', 'jasa edit', 'freelance project', 'project fee', 'milestone bayar', 'gaji harian',
        'gaji borongan', 'upah harian', 'lembur weekend', 'thr karyawan', 'bonus tahunan', 'bonus kinerja', 'apotek online', 'beli obat',
        'resep dokter', 'tebus resep', 'tes antigen', 'tes pcr', 'rapid test', 'cek darah lengkap', 'facial treatment', 'chemical peeling',
        'skin treatment', 'hair treatment', 'creambath', 'smoothing', 'rebonding', 'cat rambut', 'tukang listrik panggilan', 'tukang ac',
        'servis ac', 'isi freon ac', 'cuci ac', 'steam ac', 'filter air', 'filter ro', 'tanki air', 'pompa air',
        'sumur bor', 'genteng bocor', 'uang buku', 'seragam sekolah', 'pramuka', 'kegiatan sekolah', 'ekskul', 'outing sekolah',
        'study tour', 'mainan edukasi', 'mainan Montessori', 'buku cerita', 'nonton bioskop', 'streaming film', 'langganan viu', 'iqiyi vip',
        'top up game', 'diamond ml', 'uc pubg', 'steam wallet', 'voucher game', 'google play gift', 'steam sale', 'traktir temen',
        'traktir kantor', 'arisan', 'arisan rutin', 'kado ultah', 'kado wisuda', 'parcel lebaran', 'hampers lebaran', 'parsel',
        'bingkisan', 'reksa dana', 'obligasi', 'sbn ritel', 'sukuk', 'deposito berjangka', 'tabungan emas', 'emas antam',
        'emas logam mulia', 'cicilan emas', 'abis gajian', 'habis gaji', 'cair gaji', 'gaji cair', 'transfer dulu', 'cobain beli',
        'nyobain', 'beli karena diskon', 'co', 'diskonan', 'diskonan akhir tahun', 'pelunasan hutang', 'lunas hutang', 'balikin pinjaman',
        'dapat pinjaman', 'terima pinjaman', 'pinjaman dari', 'pinjam dari', 'hutang dari', 'dipinjemin', 'kasih pinjam', 'kasih pinjaman',
        'pinjamkan ke', 'pijemin ke', 'piutang ke', 'pinjam ke', 'pelunasan piutang', 'terima pelunasan',
    ],

    'short_ambiguous_transaction_keywords' => [
        'air', 'teh', 'gas', 'es', 'pot', 'cat', 'map', 'nasi', 'mie', 'roti', 'kue', 'susu', 'obat', 'rak', 'sop', 'jus', 'kopi', 'ml', 'ff', 'ps', 'latte', 'soda', 'abc', 'meja', 'kursi', 'lampu', 'sofa', 'print', 'tinta', 'ikan', 'ayam', 'daging', 'sayur', 'telur', 'tahu', 'tempe', 'gula', 'beras', 'minyak',
    ],

];
