<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Merchant → Category Mapping
    |--------------------------------------------------------------------------
    |
    | Mapping nama merchant/brand/tempat → category_type.
    | Digunakan oleh CategoryMappingService::resolveByMerchant()
    | untuk memberikan kategori yang lebih akurat berdasarkan merchant.
    |
    | Urutan TIDAK menentukan prioritas — resolver menggunakan weighted matching
    | (frasa terpanjang yang match = pemenang).
    |
    | Format: 'keyword merchant' => 'category_type'
    |
    */

    'merchants' => [

        // ── F&B: Restoran & Fast Food ──
        'kfc' => 'pengeluaran_makanan',
        'mcd' => 'pengeluaran_makanan',
        'mcdonalds' => 'pengeluaran_makanan',
        'mcdonald' => 'pengeluaran_makanan',
        'burger king' => 'pengeluaran_makanan',
        'bk' => 'pengeluaran_makanan',
        'pizza hut' => 'pengeluaran_makanan',
        'phd' => 'pengeluaran_makanan',
        'dominos' => 'pengeluaran_makanan',
        'hokben' => 'pengeluaran_makanan',
        'hoka hemto' => 'pengeluaran_makanan',
        'yoshinoya' => 'pengeluaran_makanan',
        'solaria' => 'pengeluaran_makanan',
        'marugame' => 'pengeluaran_makanan',
        'subway' => 'pengeluaran_makanan',
        'jco' => 'pengeluaran_makanan',
        'dunkin' => 'pengeluaran_makanan',
        'dunkin donuts' => 'pengeluaran_makanan',
        'a&w' => 'pengeluaran_makanan',
        'wendys' => 'pengeluaran_makanan',
        'carls jr' => 'pengeluaran_makanan',
        'popeyes' => 'pengeluaran_makanan',
        'chatime' => 'pengeluaran_makanan',
        'gong cha' => 'pengeluaran_makanan',
        'coco' => 'pengeluaran_makanan',
        'sharetea' => 'pengeluaran_makanan',
        'teazzi' => 'pengeluaran_makanan',
        'xiboba' => 'pengeluaran_makanan',
        'mixue' => 'pengeluaran_makanan',
        'mixue boba' => 'pengeluaran_makanan',

        // ── F&B: Kopi ──
        'starbucks' => 'pengeluaran_makanan',
        'sbux' => 'pengeluaran_makanan',
        'sbx' => 'pengeluaran_makanan',
        'janji jiwa' => 'pengeluaran_makanan',
        'kopi kenangan' => 'pengeluaran_makanan',
        'kenangan' => 'pengeluaran_makanan',
        'fore' => 'pengeluaran_makanan',
        'fore coffee' => 'pengeluaran_makanan',
        'tomoro' => 'pengeluaran_makanan',
        'tomoro coffee' => 'pengeluaran_makanan',
        'max coffee' => 'pengeluaran_makanan',
        'tuku' => 'pengeluaran_makanan',
        'anomali' => 'pengeluaran_makanan',
        'giyanti' => 'pengeluaran_makanan',
        'one fifteen' => 'pengeluaran_makanan',
        'excelso' => 'pengeluaran_makanan',
        'coffee bean' => 'pengeluaran_makanan',
        'coffee beanery' => 'pengeluaran_makanan',
        'glodok' => 'pengeluaran_makanan',
        'kopitiam' => 'pengeluaran_makanan',

        // ── F&B: Warung & Restoran Umum ──
        'warteg' => 'pengeluaran_makanan',
        'warung' => 'pengeluaran_makanan',
        'resto' => 'pengeluaran_makanan',
        'restoran' => 'pengeluaran_makanan',
        'cafe' => 'pengeluaran_makanan',
        'kafe' => 'pengeluaran_makanan',
        'kantin' => 'pengeluaran_makanan',
        'foodcourt' => 'pengeluaran_makanan',
        'food court' => 'pengeluaran_makanan',
        'rm ' => 'pengeluaran_makanan',
        'padang' => 'pengeluaran_makanan',
        'masakan padang' => 'pengeluaran_makanan',

        // ── F&B: Platform Delivery ──
        'gofood' => 'pengeluaran_makanan',
        'grabfood' => 'pengeluaran_makanan',
        'shopeefood' => 'pengeluaran_makanan',
        'traveloka eats' => 'pengeluaran_makanan',

        // ── Marketplace & E-commerce ──
        'shopee' => 'pengeluaran_belanja',
        'tokopedia' => 'pengeluaran_belanja',
        'tokped' => 'pengeluaran_belanja',
        'bukalapak' => 'pengeluaran_belanja',
        'blibli' => 'pengeluaran_belanja',
        'lazada' => 'pengeluaran_belanja',
        'bli bli' => 'pengeluaran_belanja',
        'tiktok shop' => 'pengeluaran_belanja',
        'zalora' => 'pengeluaran_belanja',
        'sociolla' => 'pengeluaran_belanja',
        'bibit' => 'pengeluaran_investasi',
        'stockbit' => 'pengeluaran_investasi',
        'pluang' => 'pengeluaran_investasi',
        'tokocrypto' => 'pengeluaran_investasi',
        'pintu' => 'pengeluaran_investasi',
        'indodax' => 'pengeluaran_investasi',

        // ── Minimarket & Grocery ──
        'indomaret' => 'pengeluaran_belanja',
        'alfamart' => 'pengeluaran_belanja',
        'alfamidi' => 'pengeluaran_belanja',
        'alfa express' => 'pengeluaran_belanja',
        'family mart' => 'pengeluaran_belanja',
        'lawson' => 'pengeluaran_belanja',
        '7eleven' => 'pengeluaran_belanja',
        '7-eleven' => 'pengeluaran_belanja',
        'indogrosir' => 'pengeluaran_belanja',
        'transmart' => 'pengeluaran_belanja',
        'carrefour' => 'pengeluaran_belanja',
        'hypermart' => 'pengeluaran_belanja',
        'superindo' => 'pengeluaran_belanja',
        'ranch market' => 'pengeluaran_belanja',
        'farmers market' => 'pengeluaran_belanja',
        'grand lucky' => 'pengeluaran_belanja',
        'lotte mart' => 'pengeluaran_belanja',
        'giant' => 'pengeluaran_belanja',

        // ── Transport: Ride-hailing ──
        'grab' => 'pengeluaran_transport',
        'gojek' => 'pengeluaran_transport',
        'gocar' => 'pengeluaran_transport',
        'grabcar' => 'pengeluaran_transport',
        'grab bike' => 'pengeluaran_transport',
        'maxim' => 'pengeluaran_transport',
        'indriver' => 'pengeluaran_transport',
        'bluebird' => 'pengeluaran_transport',
        'express' => 'pengeluaran_transport',
        'silverbird' => 'pengeluaran_transport',

        // ── Transport: Umum ──
        'transjakarta' => 'pengeluaran_transport',
        'busway' => 'pengeluaran_transport',
        'mrt' => 'pengeluaran_transport',
        'lrt' => 'pengeluaran_transport',
        'krl' => 'pengeluaran_transport',
        'commuterline' => 'pengeluaran_transport',
        'commuter line' => 'pengeluaran_transport',
        'kereta api' => 'pengeluaran_transport',
        'ka ' => 'pengeluaran_transport',
        'tiket.com' => 'pengeluaran_transport',
        'traveloka' => 'pengeluaran_transport',
        'tiket kereta' => 'pengeluaran_transport',
        'tiket pesawat' => 'pengeluaran_transport',

        // ── Transport: SPBU ──
        'pertamina' => 'pengeluaran_transport',
        'spbu' => 'pengeluaran_transport',
        'shell' => 'pengeluaran_transport',
        'bp' => 'pengeluaran_transport',
        'vivo' => 'pengeluaran_transport',
        'total' => 'pengeluaran_transport',

        // ── Kesehatan ──
        'kimia farma' => 'pengeluaran_kesehatan',
        'guardian' => 'pengeluaran_kesehatan',
        'century' => 'pengeluaran_kesehatan',
        'k24' => 'pengeluaran_kesehatan',
        'apotek' => 'pengeluaran_kesehatan',
        'rumah sakit' => 'pengeluaran_kesehatan',
        'rs ' => 'pengeluaran_kesehatan',
        'rsia' => 'pengeluaran_kesehatan',
        'klinik' => 'pengeluaran_kesehatan',
        'lab klinik' => 'pengeluaran_kesehatan',
        'prodia' => 'pengeluaran_kesehatan',
        'pramita' => 'pengeluaran_kesehatan',
        'halodoc' => 'pengeluaran_kesehatan',
        'goapotik' => 'pengeluaran_kesehatan',
        'grabhealth' => 'pengeluaran_kesehatan',

        // ── Hiburan & Streaming ──
        'netflix' => 'pengeluaran_langganan',
        'spotify' => 'pengeluaran_langganan',
        'youtube premium' => 'pengeluaran_langganan',
        'youtube music' => 'pengeluaran_langganan',
        'disney+' => 'pengeluaran_langganan',
        'disney plus' => 'pengeluaran_langganan',
        'hbo' => 'pengeluaran_langganan',
        'hbomax' => 'pengeluaran_langganan',
        'prime video' => 'pengeluaran_langganan',
        'amazon prime' => 'pengeluaran_langganan',
        'viu' => 'pengeluaran_langganan',
        'wetv' => 'pengeluaran_langganan',
        'iqiyi' => 'pengeluaran_langganan',
        'bstation' => 'pengeluaran_langganan',
        'bilibili' => 'pengeluaran_langganan',
        'vidio' => 'pengeluaran_langganan',
        'apple music' => 'pengeluaran_langganan',
        'tidal' => 'pengeluaran_langganan',
        'deezer' => 'pengeluaran_langganan',
        'joox' => 'pengeluaran_langganan',
        'steam' => 'pengeluaran_hiburan',
        'playstation' => 'pengeluaran_hiburan',
        'ps store' => 'pengeluaran_hiburan',
        'xbox' => 'pengeluaran_hiburan',
        'nintendo' => 'pengeluaran_hiburan',
        'epic games' => 'pengeluaran_hiburan',
        'garena' => 'pengeluaran_hiburan',
        'mobile legends' => 'pengeluaran_hiburan',
        'mlbb' => 'pengeluaran_hiburan',
        'pubg' => 'pengeluaran_hiburan',
        'genshin' => 'pengeluaran_hiburan',
        'bioskop' => 'pengeluaran_hiburan',
        'cinema' => 'pengeluaran_hiburan',
        'xxi' => 'pengeluaran_hiburan',
        'cgv' => 'pengeluaran_hiburan',
        'cinepolis' => 'pengeluaran_hiburan',
        'karaoke' => 'pengeluaran_hiburan',
        'inul' => 'pengeluaran_hiburan',
        'nav karaoke' => 'pengeluaran_hiburan',

        // ── E-Wallet & Pembayaran Digital ──
        'gopay' => 'pengeluaran_lainnya',
        'ovo' => 'pengeluaran_lainnya',
        'dana' => 'pengeluaran_lainnya',
        'shopeepay' => 'pengeluaran_lainnya',
        'shopee pay' => 'pengeluaran_lainnya',
        'linkaja' => 'pengeluaran_lainnya',
        'link aja' => 'pengeluaran_lainnya',
        'isaku' => 'pengeluaran_lainnya',
        'doku' => 'pengeluaran_lainnya',
        'qris' => 'pengeluaran_lainnya',

        // ── Telco ──
        'telkomsel' => 'pengeluaran_pulsa_token',
        'xl' => 'pengeluaran_pulsa_token',
        'axis' => 'pengeluaran_pulsa_token',
        'indosat' => 'pengeluaran_pulsa_token',
        'tri' => 'pengeluaran_pulsa_token',
        'smartfren' => 'pengeluaran_pulsa_token',

        // ── Utilitas ──
        'pln' => 'pengeluaran_utilitas',
        'pdam' => 'pengeluaran_utilitas',
        'indihome' => 'pengeluaran_utilitas',
        'biznet' => 'pengeluaran_utilitas',
        'cbn' => 'pengeluaran_utilitas',
        'myrepublic' => 'pengeluaran_utilitas',
        'first media' => 'pengeluaran_utilitas',
        'iconnet' => 'pengeluaran_utilitas',
        'oxygen' => 'pengeluaran_utilitas',

        // ── Pendidikan ──
        'ruangguru' => 'pengeluaran_pendidikan',
        'zenius' => 'pengeluaran_pendidikan',
        'skill academy' => 'pengeluaran_pendidikan',
        'udemy' => 'pengeluaran_pendidikan',
        'coursera' => 'pengeluaran_pendidikan',
        'skillshare' => 'pengeluaran_pendidikan',
        'duolingo' => 'pengeluaran_pendidikan',

        // ── Ekspedisi & Logistik ──
        'jne' => 'pengeluaran_operasional',
        'jnt' => 'pengeluaran_operasional',
        'j&t' => 'pengeluaran_operasional',
        'sicepat' => 'pengeluaran_operasional',
        'si cepat' => 'pengeluaran_operasional',
        'anteraja' => 'pengeluaran_operasional',
        'ninja express' => 'pengeluaran_operasional',
        'ninja xpress' => 'pengeluaran_operasional',
        'pos indonesia' => 'pengeluaran_operasional',
        'tiki' => 'pengeluaran_operasional',
        'wahana' => 'pengeluaran_operasional',
        'lion parcel' => 'pengeluaran_operasional',
        'grab express' => 'pengeluaran_operasional',
        'gosend' => 'pengeluaran_operasional',

        // ── Asuransi ──
        'bpjs' => 'pengeluaran_asuransi',
        'bpjs kesehatan' => 'pengeluaran_asuransi',
        'bpjs ketenagakerjaan' => 'pengeluaran_asuransi',
        'allianz' => 'pengeluaran_asuransi',
        'prudential' => 'pengeluaran_asuransi',
        'aia' => 'pengeluaran_asuransi',
        'manulife' => 'pengeluaran_asuransi',
        'axa' => 'pengeluaran_asuransi',
        'bni life' => 'pengeluaran_asuransi',
        'bri life' => 'pengeluaran_asuransi',
        'inhealth' => 'pengeluaran_asuransi',
    ],

];
