#!/bin/bash

echo "=== DEPLOYMENT CHECKLIST ==="
echo ""
echo "Files yang perlu di-upload ke VPS:"
echo ""
echo "1. Backend (PHP):"
echo "   - routes/web.php"
echo "   - app/Http/Controllers/SubscriptionController.php"
echo "   - app/Helpers/BatchTransactionHelper.php"
echo "   - app/Jobs/ProcessIncomingMessage.php"
echo ""
echo "2. Frontend (Built Assets):"
echo "   - public/build/ (entire folder)"
echo ""
echo "3. Commands to run on VPS:"
echo "   cd ~/www/finwa.web.id"
echo "   php artisan route:clear"
echo "   php artisan cache:clear"
echo "   php artisan config:clear"
echo "   php artisan view:clear"
echo ""
echo "4. Verify routes:"
echo "   php artisan route:list | grep subscriptions"
echo ""
