#!/bin/bash

echo "=== DEPLOY FIX TO VPS ==="
echo ""
echo "File yang perlu di-upload:"
echo "  app/Helpers/WhatsAppRegistrationHelper.php"
echo ""
echo "Setelah upload, jalankan di VPS:"
echo "  cd ~/www/finwa.web.id"
echo "  php artisan cache:clear"
echo "  php artisan queue:restart"
echo ""
echo "Lalu test lagi dengan user baru:"
echo "  1. Kirim pesan dari nomor/LID yang belum terdaftar"
echo "  2. Ketik 'Daftar'"
echo "  3. Kirim nama"
echo "  4. Kirim email"
echo "  5. Seharusnya dapat kredensial login"
echo ""
